[build]
  # Directory with the built site
  publish = "."
  # Directory with the functions code
  functions = "netlify/functions"

# API redirect with absolute paths
[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/:splat"
  status = 200

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 