[build]
  # Directory with the built site
  publish = "."
  # Directory with the functions code
  functions = "netlify/functions"

# Redirect for Netlify Functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200 